image:
  file: .gitpod.Dockerfile

ports:
- port: 8080
  onOpen: open-preview
- port: 8888
  onOpen: open-browser
tasks:
- init: /workspace/covid_analysis/run.sh
  command: cp -r /covid_analysis/.jupyter /home/gitpod/
