image:
  file: .gitpod.Dockerfile

ports:
- port: 8080
  onOpen: open-preview
- port: 8888
  onOpen: open-browser
tasks:
- name: initialize
  before: chmod 755 /workspace/covid_analysis/run.sh
  init: /workspace/covid_analysis/run.sh
  command: cp -r /workspace/covid_analysis/.jupyter /home/gitpod/
